# docker-compose configuration for running SpineAI locally.
#
# Usage:
#   $ docker-compose -f local.docker-compose.yml up
#
version: '3.7'
services:
  spineai-frontend:
    image: spineai/spineai-frontend:latest
    environment:
      - NODE_ENV=docker-local
    ports:
      - "80:80"
    networks:
      - api
    restart: unless-stopped
  spineai-api:
    image: spineai/spineai-api:latest
    environment:
      - NODE_ENV=docker-local
    ports:
      - "8080:8080"
    networks:
      - api
    volumes:
      - ./local:/local
      - type: volume
        source: "database"
        target: "/database"
    restart: unless-stopped
  spineai-backend:
    image: spineai/spineai-backend:latest
    volumes:
      - type: volume
        source: "database"
        target: "/database"
      - type: bind
        source: "./config/local.backend.yml"
        target: "/app/config/dev-docker.yml"
      - "./logs:/logs"
    restart: unless-stopped
    ports:
      - "8008:8008"
    networks:
      - api
  spineai-pacs:
    image: jodogne/orthanc:1.10.1
    environment:
      ORTHANC__AUTHENTICATION_ENABLED: "true"
    ports:
      - 4242:4242
      - 8042:8042 # login port. login: orthanc/orthanc
    volumes:
      - type: bind
        source: "./config/orthanc.json5"
        target: "/etc/orthanc/orthanc.json"
      - type: volume
        source: "pacs-database"
        target: "/var/lib/othanc/db"
    restart: unless-stopped
    networks:
      - api

volumes:
  database:
    name: spineai-database
  pacs-database:
    name: spineai-pacs-database

networks:
  api:
