# Overrides to run SpineAI for UCLA.
version: '3.7'
services:
  spineai-backend:
    ports:
      - "8001:8001"
    volumes:
      - type: bind
        source: "./config/ucla.backend.yml"
        target: "/app/config/dev-docker.yml"
  spineai-frontend:
    environment:
      # - EXPRESS_PORT=80
      - NODE_ENV=docker-ucla
    # ports:
    # - "80:8081"
