[tool.poetry]
name = "spineai-dev-docs"
version = "0.1.0"
description = ""
authors = ["Billy Cao <billy@spineai.com>"]

[tool.poetry.dependencies]
python = "^3.6"
mkdocs = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
